set(HEADER_FILES
src/core/component.r.h
src/core/component.h
src/core/processor.h
src/core/processor.r.h
src/units/unit.r.h
src/units/denseunit.r.h
src/units/unit.h
src/units/denseunit.h
src/units/embedunit.h
src/units/embedunit.r.h
src/units/lstmunit.h
src/units/lstmunit.r.h
src/network/network.r.h
src/network/network.h
src/network/sequential_network.r.h
src/network/sequential_network.h
src/triggers/trigger.r.h
src/triggers/relutrigger.h
src/triggers/trigger.h
src/triggers/relutrigger.r.h
src/triggers/sigmoidtrigger.r.h
src/triggers/sigmoidtrigger.h
src/triggers/softmaxtrigger.h
src/triggers/softmaxtrigger.r.h
src/tuning/tuner.r.h
src/tuning/tuner.h
src/tuning/sgd_tuner.h
src/tuning/sgd_tuner.r.h
src/cost/mse_cost.r.h
src/cost/cost.r.h
src/cost/cost.h
src/cost/mse_cost.h
src/cost/cross_entropy_cost.r.h
src/cost/cross_entropy_cost.h
src/data/batch_sampler.h
src/data/sampler.r.h
src/data/sampler.h
src/data/batch_sampler.r.h
src/data/lm_token_sampler.h
src/data/lm_token_sampler.r.h
src/training/learning.r.h
src/training/learning.h
src/training/supervised_learning.h
src/training/supervised_learning.r.h
src/evaluation/evaluation.r.h
src/evaluation/evaluation.h
src/evaluation/accuracy_evaluation.r.h
src/evaluation/accuracy_evaluation.h
src/volume/volume.r.h
src/volume/volume.h
)
