set(HEADER_FILES 
include/core/component.r.h
include/core/component.h
include/core/processor.h
include/core/processor.r.h
include/network/network.r.h
include/network/network.h
include/network/sequential_network.r.h
include/network/sequential_network.h
include/triggers/trigger.r.h
include/triggers/relutrigger.h
include/triggers/trigger.h
include/triggers/relutrigger.r.h
include/tuning/tuner.r.h
include/tuning/tuner.h
include/tuning/sgd_tuner.h
include/tuning/sgd_tuner.r.h
include/cost/mse_cost.r.h
include/cost/cost.r.h
include/cost/cost.h
include/cost/mse_cost.h
include/data/batch_sampler.h
include/data/sampler.r.h
include/data/sampler.h
include/data/batch_sampler.r.h
include/training/learning.r.h
include/training/learning.h
include/training/supervised_learning.h
include/training/supervised_learning.r.h
include/evaluation/evaluation.r.h
include/evaluation/evaluation.h
include/evaluation/accuracy_evaluation.r.h
include/evaluation/accuracy_evaluation.h
include/units/unit.r.h
include/units/denseunit.r.h
include/units/unit.h
include/units/denseunit.h
include/volume/volume.r.h
include/volume/volume.h
)
