set(HEADER_FILES 
include/core/component.r.h
include/core/component.h
include/core/processor.h
include/core/processor.r.h
include/network/network.r.h
include/network/network.h
include/triggers/trigger.r.h
include/triggers/trigger.h
include/tuning/tuner.r.h
include/tuning/tuner.h
include/cost/cost.r.h
include/cost/cost.h
include/data/sampler.r.h
include/data/sampler.h
include/training/learning.r.h
include/training/learning.h
include/evaluation/evaluation.r.h
include/evaluation/evaluation.h
include/units/unit.r.h
include/units/unit.h
include/volume/volume.r.h
include/volume/volume.h
)
