set(SOURCE_FILES
src/core/component.c
src/core/processor.c
src/units/unit.c
src/units/dense_unit.c
src/units/embed_unit.c
src/units/lstm_unit.c
src/network/network.c
src/network/sequential_network.c
src/triggers/relutrigger.c
src/triggers/trigger.c
src/triggers/sigmoidtrigger.c
src/triggers/softmaxtrigger.c
src/tuning/tuner.c
src/tuning/sgd_tuner.c
src/cost/mse_cost.c
src/cost/cost.c
src/cost/cross_entropy_cost.c
src/data/batch_sampler.c
src/data/sampler.c
src/data/lm_token_sampler.c
src/training/learning.c
src/training/supervised_learning.c
src/evaluation/evaluation.c
src/evaluation/accuracy_evaluation.c
src/volume/volume.c
)
